encoding: UTF-8
title: "Ikkifik"

url: "ikkifik.github.io"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:year/:title"
      img_path: "/assets/images/post"
      excerpt_separator: "."
